#: import menu menu
MainWidget:


<MainWidget>:
    canvas.before:
        Rectangle:
            size: self.size
            source: 'images/bg3.jpg'
    menu_widget: menu_widget
    perspective_point_x: self.width/2
    perspective_point_y: self.height*0.75
    MenuWidget:
        id: menu_widget
    Label:
        text: root.score_txt
        font_size: dp(20)
        font_name: 'fonts/Eurostile.ttf' 
        size_hint: .2, .2
        width: 2.0
        pos_hint: { "right": 1, "top": 1}
